version: '2'
services:
    redis:
        hostname: redis
        image: redis:latest
        command: redis-server
    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
    worker:
        build:
            context: ./workers
            dockerfile: dockerfile
        env_file:
            - ../.env
        links:
            - redis
            - database
        depends_on:
            - redis
            - database
        volumes:
            - ./workers:/app/workers

